# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40586002fe5bf222c5083f8a0a3a8dddb75578766bf760de76bf52532466cf5509e0e066e0c468eea2e5cb48288545bf9fa43ea90baec9c01680d1b2606c0427

test:
  secret_key_base: a58224354b0c060090488b5f63494193e64ac531580f804074f5f2fdeb7d2c0bca08879005d69de53412d4c9ebfe281fb36c56ec2ac55321da6f651251dd51f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
